name: qwen
channels:
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch/linux-64/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2025.12.2=h06a4308_0
  - expat=2.7.3=h7354ed3_4
  - ld_impl_linux-64=2.44=h153f514_2
  - libexpat=2.7.3=h7354ed3_4
  - libffi=3.4.4=h6a678d5_1
  - libgcc=15.2.0=h69a1729_7
  - libgcc-ng=15.2.0=h166f726_7
  - libgomp=15.2.0=h4751f2c_7
  - libnsl=2.0.0=h5eee18b_0
  - libstdcxx=15.2.0=h39759b7_7
  - libstdcxx-ng=15.2.0=hc03a8fd_7
  - libuuid=1.41.5=h5eee18b_0
  - libxcb=1.17.0=h9b100fa_0
  - libzlib=1.3.1=hb25bd0a_0
  - ncurses=6.5=h7934f7d_0
  - openssl=3.0.18=hd6dcaed_0
  - pip=25.3=pyhc872135_0
  - pthread-stubs=0.3=h0ce48e5_1
  - python=3.10.19=h6fa692b_0
  - readline=8.3=hc2a1206_0
  - setuptools=80.9.0=py310h06a4308_0
  - sqlite=3.51.0=h2a70700_0
  - tk=8.6.15=h54e0aa7_0
  - tzdata=2025b=h04d1e81_0
  - wheel=0.45.1=py310h06a4308_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.6.4=h5eee18b_1
  - zlib=1.3.1=hb25bd0a_0
  - pip:
      - absl-py==2.1.0
      - accelerate==1.8.1
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.13.2
      - aiosignal==1.4.0
      - airportsdata==20250909
      - annotated-doc==0.0.4
      - annotated-types==0.7.0
      - antlr4-python3-runtime==4.9.3
      - anyio==4.12.0
      - asciitree==0.3.3
      - astor==0.8.1
      - async-timeout==5.0.1
      - attrs==25.4.0
      - av==16.0.1
      - bitsandbytes==0.46.1
      - blake3==1.0.8
      - braceexpand==0.1.7
      - cachetools==6.2.3
      - cbor2==5.7.1
      - certifi==2025.11.12
      - cffi==2.0.0
      - charset-normalizer==3.4.4
      - click==8.2.1
      - cloudpickle==3.1.2
      - compressed-tensors==0.10.2
      - contourpy==1.3.2
      - cupy-cuda12x==13.6.0
      - cycler==0.12.1
      - decorator==5.2.1
      - deepspeed==0.17.2
      - depyf==0.19.0
      - diffusers==0.35.1
      - dill==0.4.0
      - diskcache==5.6.3
      - distro==1.9.0
      - dnspython==2.8.0
      - einops==0.8.1
      - email-validator==2.3.0
      - exceptiongroup==1.3.1
      - fastapi==0.124.4
      - fastapi-cli==0.0.16
      - fastapi-cloud-cli==0.6.0
      - fastar==0.8.0
      - fasteners==0.20
      - fastrlock==0.8.3
      - filelock==3.20.0
      - flash-attn==2.8.3
      - fonttools==4.61.1
      - frozenlist==1.8.0
      - fsspec==2025.12.0
      - gguf==0.17.1
      - gitdb==4.0.12
      - gitpython==3.1.45
      - h11==0.16.0
      - h5py==3.15.1
      - hf-xet==1.2.0
      - hjson==3.1.0
      - httpcore==1.0.9
      - httptools==0.7.1
      - httpx==0.28.1
      - huggingface-hub==0.36.0
      - idna==3.11
      - imagecodecs==2025.3.30
      - imageio==2.37.2
      - imageio-ffmpeg==0.6.0
      - imgaug==0.4.0
      - importlib-metadata==8.7.0
      - interegular==0.3.3
      - jedi==0.19.2
      - jinja2==3.1.6
      - jiter==0.12.0
      - joblib==1.5.2
      - jsonschema==4.25.1
      - jsonschema-specifications==2025.9.1
      - kiwisolver==1.4.9
      - lark==1.2.2
      - lazy-loader==0.4
      - llguidance==0.7.30
      - llvmlite==0.44.0
      - lm-format-enforcer==0.10.12
      - lmdb==1.7.5
      - markdown-it-py==4.0.0
      - markupsafe==2.1.5
      - matplotlib==3.10.8
      - mdurl==0.1.2
      - mistral-common==1.8.6
      - moviepy==2.2.1
      - mpmath==1.3.0
      - msgpack==1.1.2
      - msgspec==0.20.0
      - multidict==6.7.0
      - nest-asyncio==1.6.0
      - networkx==3.4.2
      - ninja==1.13.0
      - numba==0.61.2
      - numcodecs==0.13.1
      - numpy==1.26.4
      - nvidia-cublas-cu12==12.8.3.14
      - nvidia-cuda-cupti-cu12==12.8.57
      - nvidia-cuda-nvrtc-cu12==12.8.61
      - nvidia-cuda-runtime-cu12==12.8.57
      - nvidia-cudnn-cu12==9.7.1.26
      - nvidia-cufft-cu12==11.3.3.41
      - nvidia-cufile-cu12==1.13.0.11
      - nvidia-curand-cu12==10.3.9.55
      - nvidia-cusolver-cu12==11.7.2.55
      - nvidia-cusparse-cu12==12.5.7.53
      - nvidia-cusparselt-cu12==0.6.3
      - nvidia-ml-py==13.580.82
      - nvidia-nccl-cu12==2.26.2
      - nvidia-nvjitlink-cu12==12.8.61
      - nvidia-nvtx-cu12==12.8.55
      - nvitop==1.6.1
      - omegaconf==2.3.0
      - openai==1.90.0
      - opencv-python==4.11.0.86
      - opencv-python-headless==4.11.0.86
      - outlines==0.1.11
      - outlines-core==0.2.10
      - packaging==25.0
      - parso==0.8.5
      - partial-json-parser==0.2.1.1.post7
      - peft==0.17.1
      - pillow==11.3.0
      - platformdirs==4.5.1
      - proglog==0.1.12
      - prometheus-client==0.23.1
      - prometheus-fastapi-instrumentator==7.1.0
      - propcache==0.4.1
      - protobuf==6.33.2
      - psutil==7.1.3
      - py-cpuinfo==9.0.0
      - pybase64==1.4.3
      - pycountry==24.6.1
      - pycparser==2.23
      - pydantic==2.12.5
      - pydantic-core==2.41.5
      - pydantic-extra-types==2.10.6
      - pygments==2.19.2
      - pyparsing==3.2.5
      - python-dateutil==2.9.0.post0
      - python-dotenv==1.2.1
      - python-json-logger==4.0.0
      - python-multipart==0.0.20
      - pyyaml==6.0.3
      - pyzmq==27.1.0
      - qwen-vl-utils==0.0.14
      - ray==2.52.1
      - referencing==0.37.0
      - regex==2025.11.3
      - requests==2.32.5
      - rich==14.2.0
      - rich-toolkit==0.17.0
      - rignore==0.7.6
      - rpds-py==0.30.0
      - safetensors==0.7.0
      - scikit-image==0.25.2
      - scikit-learn==1.7.2
      - scipy==1.15.3
      - sentencepiece==0.2.1
      - sentry-sdk==2.47.0
      - shapely==2.1.2
      - shellingham==1.5.4
      - six==1.17.0
      - smmap==5.0.2
      - sniffio==1.3.1
      - soundfile==0.13.1
      - soxr==1.0.0
      - starlette==0.50.0
      - sympy==1.14.0
      - threadpoolctl==3.6.0
      - tifffile==2025.5.10
      - tiktoken==0.12.0
      - timm==1.0.15
      - tokenizers==0.22.1
      - tomli==2.3.0
      - torch==2.7.1+cu128
      - torchaudio==2.7.1+cu128
      - torchvision==0.22.1+cu128
      - tqdm==4.67.1
      - transformers==4.57.3
      - triton==3.3.1
      - typer==0.20.0
      - typing-extensions==4.15.0
      - typing-inspection==0.4.2
      - urllib3==2.6.2
      - uvicorn==0.38.0
      - uvloop==0.22.1
      - vllm==0.10.0
      - wandb==0.23.1
      - watchfiles==1.1.1
      - webdataset==1.0.2
      - websockets==15.0.1
      - xformers==0.0.31
      - xgrammar==0.1.21
      - yarl==1.22.0
      - zarr==2.18.3
      - zipp==3.23.0
prefix: /home/jiangjiahao/miniconda3/envs/qwen
